name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
pages_build_output_dir = "."

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "hymsgook.qzz.io"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "hymsgook.qzz.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.hymsgook.qzz.io", custom_domain = true },
  { pattern = "quay.hymsgook.qzz.io", custom_domain = true },
  { pattern = "gcr.hymsgook.qzz.io", custom_domain = true },
  { pattern = "k8s-gcr.hymsgook.qzz.io", custom_domain = true },
  { pattern = "k8s.hymsgook.qzz.io", custom_domain = true },
  { pattern = "ghcr.hymsgook.qzz.io", custom_domain = true },
  { pattern = "cloudsmith.hymsgook.qzz.io", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.hymsgook.qzz.io", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
